# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:50:10+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetglobaltimeGetResponse(BaseModel):
    ClockTime: Optional[str] = None
    Code: Optional[str] = None
    Credits: Optional[str] = None
    CurrentDate: Optional[str] = None
    CurrentTime: Optional[str] = None
    Day: Optional[str] = None
    Hour: Optional[str] = None
    Locale: Optional[str] = None
    Minute: Optional[str] = None
    Month: Optional[str] = None
    MonthNumber: Optional[str] = None
    Second: Optional[str] = None
    TimeStamp: Optional[str] = None
    Weekday: Optional[str] = None
    Year: Optional[str] = None
    Zone: Optional[str] = None
